/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CustomerServiceRouteImport } from './routes/customer-service'
import { Route as CustomerChatRouteImport } from './routes/customer-chat'
import { Route as CollabRouteImport } from './routes/collab'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AiCallRouteImport } from './routes/ai-call'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingStepRouteImport } from './routes/onboarding.$step'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerServiceRoute = CustomerServiceRouteImport.update({
  id: '/customer-service',
  path: '/customer-service',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerChatRoute = CustomerChatRouteImport.update({
  id: '/customer-chat',
  path: '/customer-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabRoute = CollabRouteImport.update({
  id: '/collab',
  path: '/collab',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCallRoute = AiCallRouteImport.update({
  id: '/ai-call',
  path: '/ai-call',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/onboarding/$step',
  path: '/onboarding/$step',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/achievements': typeof AchievementsRoute
  '/ai-call': typeof AiCallRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/collab': typeof CollabRoute
  '/customer-chat': typeof CustomerChatRoute
  '/customer-service': typeof CustomerServiceRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/more': typeof MoreRoute
  '/pricing': typeof PricingRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/onboarding/$step': typeof OnboardingStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/achievements': typeof AchievementsRoute
  '/ai-call': typeof AiCallRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/collab': typeof CollabRoute
  '/customer-chat': typeof CustomerChatRoute
  '/customer-service': typeof CustomerServiceRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/more': typeof MoreRoute
  '/pricing': typeof PricingRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/onboarding/$step': typeof OnboardingStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/achievements': typeof AchievementsRoute
  '/ai-call': typeof AiCallRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/collab': typeof CollabRoute
  '/customer-chat': typeof CustomerChatRoute
  '/customer-service': typeof CustomerServiceRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/more': typeof MoreRoute
  '/pricing': typeof PricingRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/onboarding/$step': typeof OnboardingStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/achievements'
    | '/ai-call'
    | '/calendar'
    | '/chat'
    | '/collab'
    | '/customer-chat'
    | '/customer-service'
    | '/home'
    | '/library'
    | '/more'
    | '/pricing'
    | '/signin'
    | '/signup'
    | '/onboarding/$step'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/achievements'
    | '/ai-call'
    | '/calendar'
    | '/chat'
    | '/collab'
    | '/customer-chat'
    | '/customer-service'
    | '/home'
    | '/library'
    | '/more'
    | '/pricing'
    | '/signin'
    | '/signup'
    | '/onboarding/$step'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/achievements'
    | '/ai-call'
    | '/calendar'
    | '/chat'
    | '/collab'
    | '/customer-chat'
    | '/customer-service'
    | '/home'
    | '/library'
    | '/more'
    | '/pricing'
    | '/signin'
    | '/signup'
    | '/onboarding/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AchievementsRoute: typeof AchievementsRoute
  AiCallRoute: typeof AiCallRoute
  CalendarRoute: typeof CalendarRoute
  ChatRoute: typeof ChatRoute
  CollabRoute: typeof CollabRoute
  CustomerChatRoute: typeof CustomerChatRoute
  CustomerServiceRoute: typeof CustomerServiceRoute
  HomeRoute: typeof HomeRoute
  LibraryRoute: typeof LibraryRoute
  MoreRoute: typeof MoreRoute
  PricingRoute: typeof PricingRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  OnboardingStepRoute: typeof OnboardingStepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-service': {
      id: '/customer-service'
      path: '/customer-service'
      fullPath: '/customer-service'
      preLoaderRoute: typeof CustomerServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-chat': {
      id: '/customer-chat'
      path: '/customer-chat'
      fullPath: '/customer-chat'
      preLoaderRoute: typeof CustomerChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab': {
      id: '/collab'
      path: '/collab'
      fullPath: '/collab'
      preLoaderRoute: typeof CollabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-call': {
      id: '/ai-call'
      path: '/ai-call'
      fullPath: '/ai-call'
      preLoaderRoute: typeof AiCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/onboarding/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AchievementsRoute: AchievementsRoute,
  AiCallRoute: AiCallRoute,
  CalendarRoute: CalendarRoute,
  ChatRoute: ChatRoute,
  CollabRoute: CollabRoute,
  CustomerChatRoute: CustomerChatRoute,
  CustomerServiceRoute: CustomerServiceRoute,
  HomeRoute: HomeRoute,
  LibraryRoute: LibraryRoute,
  MoreRoute: MoreRoute,
  PricingRoute: PricingRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  OnboardingStepRoute: OnboardingStepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
